### ISSUE TITLE
多重update_name

### ISSUE THREAD

**Issue by nokok** [At1s/Arbis#13]
update_nameで複数のコマンドを同時に送信した場合、
update_name
--name
--update_name
-n
の順で読まれて、ヒットしたらそれ以降は無視されるような挙動をするようです。

例：
Req
https://twitter.com/noko_k/status/765202729543225344

Res
https://twitter.com/AtisRb/status/765202738841989120

今のところクリティカルなものではないので優先度低かと思われます

**Comment by At1s** [comment]
報告ありがとうございます
### 問題点
update_nameで、コマンドによってパースされる名前が違う
### 解決策
parserの処理を変更する
- 処理内の引数で受け取ったコマンド順でパースするのではなく、リプライの中身順で先頭からパースしていく
