### ISSUE TITLE
bundler のサポートについて

### ISSUE THREAD

**Issue by Gomasy** [At1s/Arbis#14]
gem を システム環境にインストールしたくない人、又は bundle install でサクッとデプロイしたい人がいることも考えて Gemfile の追加をするべきだと思います。

### For example
```
source "https://rubygems.org"

gem "twitter", ">=5.16.0"
gem "hashie", ">=3.4.4"
gem "docomoru", ">=0.1.3"
gem "weather-report", ">=0.3.7"
```

**Comment by At1s** [comment]
報告ありがとうございます  
次のcommitで追加します

**Comment by At1s** [comment]
Gemfileを追加しました  
c8c83f7617898066822f823920f535bc3be981a7

**Comment by Gomasy** [comment]
:+1:
